export const HANDLE_USER_SIGN_IN = {
    START_SIGN_IN_EMAIL: 'START_SIGN_IN_EMAIL',
    SUCCESS_SIGN_IN_EMAIL: 'SUCCESS_SIGN_IN_EMAIL',
    FAILURE_SIGN_IN_EMAIL: 'FAILURE_SIGN_IN_EMAIL',
    START_UPLOAD_PHOTO: 'START_UPLOAD_PHOTO',
    SUCCESS_UPLOAD_PHOTO: 'SUCCESS_UPLOAD_PHOTO',
    FAILURE_UPLOAD_PHOTO: 'FAILURE_UPLOAD_PHOTO',
    START_USER_SIGN_OUT: 'START_USER_SIGN_OUT',
    SUCCESS_USER_SIGN_OUT: 'SUCCESS_USER_SIGN_OUT',
    FAILURE_USER_SIGN_OUT: 'FAILURE_USER_SIGN_OUT',
}

export const HANDLE_USER_SIGN_UP = {
    START_SIGN_UP_EMAIL: 'START_SIGN_UP_EMAIL',
    SUCCESS_SIGN_UP_EMAIL: 'SUCCESS_SIGN_UP_EMAIL',
    FAILURE_SIGN_UP_EMAIL: 'FAILURE_SIGN_UP_EMAIL',
}