export const HANDLE_USER_SIGN_IN = {
    START_SIGN_IN_EMAIL: 'START_SIGN_IN_EMAIL',
    SUCCESS_SIGN_IN_EMAIL: 'SUCCESS_SIGN_IN_EMAIL',
    FAILURE_SIGN_IN_EMAIL: 'FAILURE_SIGN_IN_EMAIL',
    USER_SIGN_OUT: 'USER_SIGN_OUT',
    GET_USER_NAME: 'GET_USER_NAME',
    UPLOAD_USER_PHOTO:  'UPLOAD_USER_PHOTO'
}